export const dateGeodiscoveries = [
    {
        id: 1,
        title: 'Город 1 Город 1 Город 1 Город 1 Город 1 Город 1Город 1',
        img: '#',
        text: 'много много текста много много текста много много текста много много текста много много текста',
        category: 'museum',
        favorite: true,
        rating: 10,
    },
    {
        id: 2,
        title: 'Город 2',
        img: '#',
        text: 'много много текста',
        category: 'park',
        favorite: false,
        rating: 4,
    },
    {
        id: 3,
        title: 'Город 3',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 2,
    },
    {
        id: 4,
        title: 'Город 4',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 1,
    },
    {
        id: 5,
        title: 'Город 5',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 5,
    },
    {
        id: 6,
        title: 'Город 6',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 4,
    },
    {
        id: 7,
        title: 'Город 7',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 4,
    },
    {
        id: 8,
        title: 'Город 8',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 4,
    },
    {
        id: 9,
        title: 'Город 9',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 4,
    },
    {
        id: 10,
        title: 'Город 10',
        img: '#',
        text: 'много много текста',
        category: 'museum',
        favorite: false,
        rating: 4,
    },
]